file_format: "1"
id: leko_pona
name: leko pona
type: shield
url: https://github.com/CrispyPin/zmk-config/
requires:
  - pro_micro
exposes:
features:
  - keys
siblings:
  - leko_pona_left
  - leko_pona_right
